config/routes.rb
Rails.application.routes.draw do

  resources :nearby_campaigns, only: :index

  get "/auth/twitter", as: :sign_in_with_twitter

  get "/auth/:provider/callback" => "callbacks#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :discussions do
    resources :comments, only: [:create]
  end
  resources :users, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :campaigns do
    resources :publishings, only: [:create]
    resources :cancellings, only: [:create]
    resources :comments,    only: [:create]
    resources :pledges,     only: [:create]
  end

  resources :pledges, only: [] do
    resources :payments, only: [:new, :create]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :campaigns
    end
  end

  root "campaigns#index"

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @pledge = Pledge.find(params[:pledge_id])
  end

  def create
    @pledge = Pledge.find params[:pledge_id]

    service = Payments::CreatePayment.new(pledge:       @pledge,
                                          user:         current_user,
                                          stripe_token: params[:stripe_token])
    if service.call
      redirect_to @pledge.campaign, notice: "Payment confirmed!"
    else
      flash[:alert] = "Something went wrong"
      render :new
    end
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/new.html.erb
<h1>Pay For your Pledge</h1>

<%= form_tag pledge_payments_path(@pledge), id: "submission-form" do %>
  <%= hidden_field_tag :stripe_token %>
<% end %>

<div id="stripe-error-message"></div>
<%= form_tag "", id: "stripe-token-form" do %>
  <div class="form-group">
    <label for="card-number">Card Number</label>
    <input id="card-number" class="form-control">
  </div>
  <div class="form-group">
    <label>Expiry</label>
    <%= select_month(Date.today, add_month_numbers: true) %>
    <%= select_year(Date.today, start_year: Date.today.year,
                                end_year: Date.today.year + 10) %>
  </div>
  <div class="form-group">
    <label for="cvc">CVC</label>
    <input id="cvc" class="form-control">
  </div>
  <div class="form-group">
    <%= submit_tag "Submit", class: "btn btn-primary" %>
  </div>
<% end %>