config/routes.rb
Rails.application.routes.draw do

  resources :nearby_campaigns, only: :index

  get "/auth/twitter", as: :sign_in_with_twitter

  get "/auth/:provider/callback" => "callbacks#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :discussions do
    resources :comments, only: [:create]
  end
  resources :users, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :campaigns do
    resources :publishings, only: [:create]
    resources :cancellings, only: [:create]
    resources :comments,    only: [:create]
    resources :pledges,     only: [:create]
  end

  resources :pledges, only: [] do
    resources :payments, only: [:new, :create]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :campaigns
    end
  end

  root "campaigns#index"

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  belongs_to :user

  has_many :rewards, dependent: :destroy
  # this allows you to pass in special parameters rewards_attributes which
  # can contain one or more rewards to be automatically created right after
  # creating the campaign
  # reject_if: :all_blank option will make it so if you pass it a set of blank
  # attributes, it will just ignore that set instead of attempting to create it
  # so it won't fail validations with the reward model
  accepts_nested_attributes_for :rewards, reject_if: :all_blank,
                                allow_destroy: true

  has_many :comments, as: :commentable, dependent: :destroy

  # address is a field in our database in this case. We expect the user to
  # provide the full address location of the campaign
  geocoded_by :address               # can also be an IP address
  # Ideally you will make the geocoding happen in the background
  # because it connects to a third party service. So you shouldn't have the
  # web request waitng for that.
  after_validation :geocode


  validates :title, presence: true, uniqueness: true
  validates :goal, presence: true, numericality: {greater_than: 10}
  validates :description, presence: true
  validates :rewards, presence: true

  scope :published, lambda { where(aasm_state: :published) }
  # def self.published
  #   where(aasm_state: :published)
  # end

  include AASM

  # the whiny_transitions option when assigned to false it makes it so AASM
  # doesn't throw an exception when you try to do an invalid transition such
  # as trying to call .fund when the campaign is in draft state
  aasm whiny_transitions: false do
    state :draft, initial: true
    state :published
    state :funded
    state :unfunded
    state :cancelled
    state :archived

    event :publish do
      transitions from: :draft, to: :published
    end

    event :fund do
      transitions from: :published, to: :funded
    end

    event :expire do
      transitions from: :published, to: :unfunded
    end

    event :archive do
      transitions from: [:funded, :unfunded, :published], to: :archived
    end

    event :cancel do
      transitions from: :published, to: :cancelled
    end

  end


end

app/controllers/api/v1/campaigns_controller.rb
class Api::V1::CampaignsController < ApplicationController
  before_action :authorize

  def index
    @campaigns = Campaign.includes(:user, :comments).published.
                  order(:created_at).references(:user, :comments).decorate
  end

  def show
    @campaign = Campaign.find params[:id]
    render json: @campaign
  end

  private

  def authorize
    @user = User.find_by_api_key params[:api_key]
    head :unauthorized unless @user
  end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :find_campaign, only: [:show, :update, :destroy, :edit]

  DEFAULT_REWARD_FIELDS_COUNT = 2

  def index
    @campaigns = Campaign.includes(:user, :comments).published.
                  order(:created_at).references(:user, :comments).decorate
    respond_to do |format|
      format.json { render json: @campaigns }
      format.html { render }
    end
  end

  def new
    @campaign = Campaign.new
    DEFAULT_REWARD_FIELDS_COUNT.times { @campaign.rewards.build }
  end

  def create
    service = Campaigns::CreateCampaign.new(user:   current_user,
                                            params: campaign_params)
    if service.call
      redirect_to campaign_path(service.campaign), notice: "Campaign created!"
    else
      @campaign = service.campaign
      # When attempting to save, Rails will automatially build a number of
      # rewards that haven't been rejected (for example, they're all blank)
      # we need to build the difference between what got automatially built
      # and our desired number which is 2 in this case
      number_to_build = DEFAULT_REWARD_FIELDS_COUNT - @campaign.rewards.size
      number_to_build.times { @campaign.rewards.build }
      render :new
    end
  end

  def show
    @campaign = @campaign.decorate
    @comment  = Comment.new
    @pledge   = Pledge.new
    respond_to do |format|
      format.html { render }
      format.json { render json: {campaign: @campaign,
                                  rewards:  @campaign.rewards,
                                  comments: @campaign.comments} }
    end
  end

  def edit
    unless current_user == @campaign.user
      redirect_to root_path, alert: "Access denied!"
    end
  end

  def update
    if current_user == @campaign.user
      if @campaign.update(campaign_params)
        redirect_to @campaign, notice: "Campaign Created!"
      else
        render :edit
      end
    else
      redirect_to root_path, alert: "Access denied!"
    end
  end

  def destroy
    if current_user == @campaign.user
      @campaign.destroy
      redirect_to campaigns_path, notice: "Campaign deleted!"
    else
      redirect_to root_path, alert: "Access denied!"
    end
  end

  private

  def campaign_params
    params.require(:campaign).permit(:title, :description, :goal, :end_date,
                                     :address, rewards_attributes:
                                        [:amount, :description, :id, :_destroy])
  end

  def find_campaign
    @campaign = Campaign.find params[:id]
  end

end

app/helpers/api/v1/campaigns_helper.rb
module Api::V1::CampaignsHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  def state_class(state)
    case state
    when "cancelled"
      "label-danger"
    when "published"
      "label-success"
    when "funded"
      "label-success"
    when "unfunded"
      "label-danger"
    when "archived"
      "label-warning"
    when "draft"
      "label-primary"
    else
      "label-default"
    end
  end
end

app/views/campaigns/_form.html.erb
<%= simple_form_for @campaign do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :goal %>
  <%= f.input :address, hint: "full address including postal/zip code" %>
  <%= f.input :end_date %>
  <!-- <% if @campaign.errors.messages[:rewards] %>
    <div>
      <%= @campaign.errors.messages[:rewards].join(", ") %>
    </div>
  <% end %> -->
  <div class="row">
    <h2>Rewards</h2>
    <div class="links col-md-12">
      <div class="clearfix"></div>
      <%= link_to_add_association 'add reward', f, :rewards,
            class: "btn btn-primary",
             data: {"association-insertion-method" => :after} %>
    </div>
    <%= f.error :rewards %>
    <%= f.simple_fields_for :rewards do |r| %>
      <%= render "reward_fields", f: r %>
    <% end %>
  </div>
  <%= f.button :submit %>
<% end %>

app/views/campaigns/_reward_fields.html.erb
<div class="col-md-4 nested-fields">
  <%= f.input :amount %>
  <%= f.input :description %>
  <%#= f.input :_destroy, as: :boolean %>
  <%= link_to_remove_association "remove reward", f,
              class: "btn btn-danger btn-sm" %>
</div>

app/views/campaigns/edit.html.erb
<h1>Edit Campaign</h1>

<%= render "form" %>

app/views/campaigns/index.html.erb
<h1>Welcome to Fund.sy</h1>
<h2>All campaigns</h2>
<% @campaigns.each do |campaign| %>
  <%= cache campaign do %>
    <h3><%= link_to campaign.title.upcase, campaign %></h3>
    <p>
      <%= campaign.truncated_description %>
    </p>
    <p>
    <% if campaign.user %>
      by <%= campaign.user.full_name %>
    <% end %>
    <%= campaign.comments.count %>
    </p>
    <hr>
  <% end %>
<% end %>

app/views/campaigns/new.html.erb
<h1>Create New Campaign</h1>

<%= render "form" %>

app/views/campaigns/show.html.erb
<h1><%= @campaign.title %></h1>
<div class="col-md-8">
  <p><%= @campaign.description %></p>
  <p>Goal: <%= @campaign.goal %></p>
  <p>End Date: <%= @campaign.end_date %></p>
  <p><%= @campaign.state_label %></p>
</div>
<div class="col-md-4">
  <div>
    <div id="map" style='height: 400px;'></div>
  </div>
</div>
<hr>

<% @campaign.rewards.each do |reward| %>
  <div class="col-md-3 well">
    <p><%= number_to_currency(reward.amount) %></p>
    <p><%= reward.description %></p>
  </div>
<% end %>

<%= @campaign.publish_button %>
<%= @campaign.cancel_button %>
<%= @campaign.edit_button %>
<%= @campaign.delete_button %>

<%= simple_form_for [@campaign, @pledge] do |f| %>
  <%= f.input :amount %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

<div class="clearfix"></div>
<h2>Comments</h2>
<%= simple_form_for [@campaign, @comment] do |f| %>
  <%= f.input :body %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

<% @campaign.comments.each do |comment| %>
  <div class="well">
    <%= comment.body %>
  </div>
<% end %>


<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers([
      {
        "lat": <%= @campaign.latitude %>,
        "lng": <%= @campaign.longitude %>,
        "infowindow": "<%= @campaign.title %>"
      }
    ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setZoom(17);
  });
</script>

app/views/campaigns/show.html.slim
h1= @campaign.title
p= @campaign.description
p 
  | Goal:
  = number_to_currency(@campaign.goal)
p
  | End Date:
  = @campaign.end_date.strftime("%Y-%b-%d %H:%M")
p
  span class="label <%= state_class(@campaign.aasm_state) %>"
    = @campaign.aasm_state
hr
- @campaign.rewards.each do |reward|
  .col-md-3.well
    p= number_to_currency(reward.amount)
    p= reward.description
- if @campaign.may_publish?
  = link_to "Publish", campaign_publishings_path(@campaign), method: :post, class: "btn btn-primary"
- if @campaign.may_cancel?
  = link_to "Cancel", campaign_cancellings_path(@campaign), method: :post,
                          class: "btn btn-danger",
                          data: {confirm: "Are you sure?"}
= link_to "Edit", edit_campaign_path(@campaign), class: "btn btn-info"
= link_to "Delete", @campaign, class: "btn btn-danger", data: {confirm: "Are you sure?"}, method: :delete
.clearfix
h2 Comments
= simple_form_for [@campaign, @comment] do |f|
  = f.input :body
  = f.submit class: "btn btn-primary"
- @campaign.comments.each do |comment|
  .well= comment.body